# Dockerfile for web container. Jacked from https://github.com/ahmetalpbalkan/docker-asp.net

# Base Docker File: Runs latest debian build, installs mono, asp.net vnext, and kre
FROM ahmetalpbalkan/aspnet-vnext
MAINTAINER Michael "ItzWarty" Yu

